#CRIAR UM DATAFRAME A PARTIR DO FUNCIONARIOS NULL
#CRIAR UMA VARIAVEL QUE CONTEM SOMENTE O DATAFRAME COM OS ELEMENTOS NULOS DA COLUNA DEPARTAMENTO PREENCHIDOS
#CRIAR UMA VARIVEL QUE CONTEM SOMENTO O DATAFRAME COM A LINHAS EM NULO DA COLUNA LUCRO REMOVIDAS

